### ISSUE TITLE
Can you help solve this problem?

### ISSUE THREAD

**Issue by scychina** [SortByte/Network-Manager#2]
Hello, I add to ipv4 route, but he does not work, you can look over there where problems

**Comment by CristianVladescu** [comment]
It's in the TODO list. There seems to be an issue with CreateIpForwardEntry2 API function.
https://github.com/SortByte/Network-Manager/blob/65f652fc558b043f6e7a860411b36e3b2b1b042e/WinLib/WinAPI/Iphlpapi.cs#L143 

I'll try push an update this week with the fix.

**Comment by scychina** [comment]
ok  thank you。

**Comment by CristianVladescu** [comment]
Fixed in [v2017.9.17.1158](https://github.com/SortByte/Network-Manager/releases/tag/v2017.9.17.1158)
