### ISSUE TITLE
Superb Tool; One cometic request

### ISSUE THREAD

**Issue by gesmith123** [SortByte/Network-Manager#3]
Thank you for the superb tool!  Is there a donation path?  
One cosmetic change request is that the right edge of all network activity level graphs windows does not have a yellow border.  Since yellow is the same color as the download graph line, it looks like the download graph is continuously spiking to maximum level,  At the same time, you may wish to remove the bottom yellow border.  The frameless gray window looks good on the black surrounding area.
This change can wait until the next release, which may include other updates.   I am having a hard time distinguishing this maintenance effort from similarly named tools in the open source world.  There may be other changes from their work that you wish to integrate also.
Keep up the good work, and thanks
![nm_yellowedge](https://user-images.githubusercontent.com/29414174/41823230-9acc3d70-77ca-11e8-9c70-4943299cdd86.png)

**Comment by CristianVladescu** [comment]
I'll look into it next week to see if it's an easy fix. Seems to be like a 1px white shadow.
If not, it will be replaced anyway since I do plan to switch to a different UI library.

**Comment by CristianVladescu** [comment]
Fixed in 2018.6.25.1158
