### ISSUE TITLE
Request: Auto Load Routes

### ISSUE THREAD

**Issue by Trip69** [SortByte/Network-Manager#6]
Hi,

by the looks of it this project is dead but does have a lot of value for those with multiple internet connections. It would nice for someone to carry it on, sadly though I code, I don't at this level

**Comment by CristianVladescu** [comment]
I actually need this myself and is easy to implement, but I reboot my system so rarely that I just load them manually at start.
I'll look into it, but the problem is that I can't push automatic updates right now, because it got broken by Google SItes.
I'll just post the release here, temporarily.

**Comment by CristianVladescu** [comment]
Added auto load option for saved route groups:
![Annotation 2020-10-04 083856](https://user-images.githubusercontent.com/13788125/95655413-c99f3000-0b0f-11eb-91a0-9eb32cc70c6d.png)
Update button doesn't work atm. Manually down the latest version.
https://github.com/SortByte/Network-Manager/releases/tag/v2020.10.8.1407
